title: My first GitHub Pages
author: gitkan
email: gitkan@domain.com
description: > # this means to ignore newlines until "baseurl:"
  lab.github.com のラーニングコンテンツ「GitHub Pages」に則って作成した、
  GitHub Pagesです。
  ここにはまだ何もありません。
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  gitkan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
